const slideData = [
    {
        id: 1,
        title: 'TechStore',
        text: 'An ecommerce developed with React.js, add products to the cart and pay with credit card.',
        url: 'https://techstore1.netlify.app',
        image: 'https://raw.githubusercontent.com/HerbertCJ/portfolio-react/main/src/images/techstore1.jpg',
    },
    {
        id: 2,
        title: 'Market List',
        text: 'Make notes before going to the supermarket.',
        url: 'https://marketlist1.netlify.app',
        image: 'https://raw.githubusercontent.com/HerbertCJ/portfolio-react/main/src/images/supermarket.jpg',
    },
    {
        id: 3,
        title: 'Card Game',
        text: 'A game in Javascript. Play against and try to get the higher card.',
        url: 'https://herbertcj.github.io/CardGame',
        image: 'https://raw.githubusercontent.com/HerbertCJ/portfolio-react/main/src/images/cardgame.jpg',
    },
    {
        id: 4,
        title: 'ProjecTec',
        text: 'Create your projects and save all data you need for planning.',
        url: 'https://projectec.netlify.app',
        image: 'https://raw.githubusercontent.com/HerbertCJ/portfolio-react/main/src/images/projectec.jpg',
    },
    {
        id: 5,
        title: 'CockTails API',
        text: 'Using a public API for fetch some cocktails.',
        url: 'https://cocktails0.netlify.app/',
        image: 'https://raw.githubusercontent.com/HerbertCJ/portfolio-react/main/src/images/cocktails.jpg',
    },
    {
        id: 6,
        title: 'JobFinder',
        text: 'Find/create jobs.',
        url: 'https://jobfinder0.netlify.app/',
        image: 'https://raw.githubusercontent.com/HerbertCJ/portfolio-react/main/src/images/jobfinder.jpg',
    },
    {
        id: 7,
        title: 'MyFood',
        text: 'Create your Menu with infos of the tabela TACO.',
        url: 'https://myfood0.netlify.app/',
        image: 'https://raw.githubusercontent.com/HerbertCJ/portfolio-react/main/src/images/myfood.jpg',
    },

]

const timelineData = [
    {
        title: 'Started my bachelor\'s degree on UNICAP University',
        date: 'Feb 2013',
        tag: '',
        color: '#fff',
        url: 'https://portal.unicap.br/',
        text: 'University Page',
    },
    {
        title: 'Got my first IT job as an Intern on Reciprev Saúde Brazil',
        date: 'Jan 2017',
        tag: '',
        color: '#fff',
        url: 'https://reciprev.recife.pe.gov.br/',
        text: 'Company Page',
    },
    {
        title: 'Got my second job as Finalcial Manager',
        date: 'Aug 2017',
        tag: '',
        color: '#fff',
        url: '',
        text: '',
    },
    {
        title: 'Got my bachelor\'s degree in Computer Science',
        date: 'Jun 2018',
        tag: '',
        color: '#fff',
        url: 'https://portal.unicap.br/',
        text: 'University Page',
    },
    {
        title: 'Started to study Java and Spring and got my certification',
        date: 'Sep 2022',
        tag: '',
        color: '#fff',
        url: 'https://www.udemy.com/certificate/UC-34eee19e-fa8c-4250-9fe0-3991a7f8ae3c/',
        text: 'Check Certification',
    },
    {
        title: 'Started to study SQL and Databases (MySQL, MongoDB) and got my certification',
        date: 'Oct 2022',
        tag: '',
        color: '#fff',
        url: 'https://www.udemy.com/certificate/UC-6cfcd520-e014-4aa8-9bad-5463554bcb06/',
        text: 'Check Certification',
    },
    {
        title: 'Got my first certification in web front end of Reponsive Web Designer, where I studied HTML5 and CSS',
        date: 'Nov 2022',
        tag: '',
        color: '#fff',
        url: 'https://www.freecodecamp.org/certification/HerbertCJ/responsive-web-design',
        text: 'Check Certification',
    },
    {
        title: 'Got my certification on JavaScript in freeCodeCamp',
        date: 'Dec 2022',
        tag: '',
        color: '#fff',
        url: 'https://www.freecodecamp.org/certification/HerbertCJ/javascript-algorithms-and-data-structures',
        text: 'Check Certification',
    },
    {
        title: 'Got my certification in Scrum on SFPC™, CertiProf, Certification Code: 82171043',
        date: 'Jan 2023',
        tag: '',
        color: '#fff',
        url: 'https://certiprof.com/',
        text: 'Check Page',
    },
    {
        title: 'Got my certification in Front End Libraries, where I studied Bootstrap, SASS, jQuery, Redux, React.js',
        date: 'Jan 2023',
        tag: '',
        color: '#fff',
        url: 'https://www.freecodecamp.org/certification/HerbertCJ/front-end-development-libraries',
        text: 'Check Certification',
    },
    {
        title: 'Working as a freelancer at the moment',
        date: 'Feb 2023',
        tag: '',
        color: '#fff',
        url: '',
        text: '',
    },
];

export { slideData, timelineData }